/** @file Publishes Archer's normalized diagnostics contracts and dispatcher. */

export {
  DiagnosticCorrelationSchema,
  DiagnosticEventInputSchema,
  DiagnosticEventRecordSchema,
  DiagnosticRecordSchema,
  DiagnosticSeveritySchema,
  DiagnosticSpanAbandonmentSchema,
  DiagnosticSpanAttributesSchema,
  DiagnosticSpanCompletionSchema,
  DiagnosticSpanEnrichmentEvidenceSchema,
  DiagnosticSpanError,
  DiagnosticSpanFailureSchema,
  DiagnosticSpanInputSchema,
  DiagnosticSpanNamespaceSchema,
  DiagnosticSpanRecordSchema,
  DiagnosticSpanSettlementSchema,
  type DiagnosticAttachOptions,
  type DiagnosticAttachmentCloseEvidence,
  type DiagnosticCorrelation,
  type DiagnosticEventInput,
  type DiagnosticEventRecord,
  type DiagnosticFilter,
  type DiagnosticHub,
  type DiagnosticRecord,
  type DiagnosticRecordBase,
  type DiagnosticSeverity,
  type DiagnosticSink,
  type DiagnosticSinkCloseEvidence,
  type Diagnostics,
  type DiagnosticsCloseEvidence,
  type DiagnosticSpan,
  type DiagnosticSpanAbandonment,
  type DiagnosticSpanAttributes,
  type DiagnosticSpanCompletion,
  type DiagnosticSpanEnrichmentEvidence,
  type DiagnosticSpanErrorCode,
  type DiagnosticSpanFailure,
  type DiagnosticSpanInput,
  type DiagnosticSpanLimits,
  type DiagnosticSpanRecord,
  type DiagnosticSpanSettlement,
  type DiagnosticSpanState,
} from './contracts.js';
export {
  createDiagnosticEvent,
  createDiagnostics,
  type DiagnosticClock,
  type DiagnosticShutdownTimer,
  type DiagnosticsOptions,
} from './hub.js';
export {
  withDiagnosticSpan,
  type DiagnosticSpanClock,
  type DiagnosticSpanIdFactory,
  type DiagnosticSpanMonotonicClock,
  type DiagnosticSpanWork,
} from './span.js';
export {
  CORE_DIAGNOSTICS_CONFORMANCE_TARGET,
  DIAGNOSTICS_CONFORMANCE_CASES,
  DIAGNOSTICS_CONFORMANCE_VERSION,
  DiagnosticsConformanceError,
  DiagnosticsConformanceReportSchema,
  requirePassingDiagnosticsConformance,
  runDiagnosticsConformance,
  type DiagnosticsConformanceCase,
  type DiagnosticsConformanceCaseId,
  type DiagnosticsConformanceCaseResult,
  type DiagnosticsConformanceImplementation,
  type DiagnosticsConformanceReport,
  type DiagnosticsConformanceTarget,
  type FailedDiagnosticsConformanceCase,
  type PassingDiagnosticsConformance,
  type PassedDiagnosticsConformanceCase,
  type RunDiagnosticsConformanceOptions,
} from './conformance.js';
