/**
 * @file Publishes Workspace contracts and the process-local reference runtime.
 *
 * Consumers may adopt private reactive file lineage without importing a model,
 * sandbox, Cell host, or managed Archer composition package.
 */

export {
  CHANGE_SET_CREATE_ACTION,
  ChangeSetSchema,
  DEFAULT_WORKSPACE_MAX_BYTES,
  DEFAULT_WORKSPACE_MAX_FILES,
  WORKSPACE_INGESTION_ACCEPT_ACTION,
  WORKSPACE_READ_ACTION,
  WORKSPACE_WRITE_ACTION,
  WorkspaceMutationSchema,
  WorkspaceIngestionCommandSchema,
  WorkspaceQuotaSchema,
  WorkspaceSnapshotSchema,
  type ChangeSet,
  type ChangeSetCreateAction,
  type ChangeSetCreateScope,
  type ChangeSetOperation,
  type ChangeSetOutcome,
  type ChangeSetRequest,
  type WorkspaceAction,
  type WorkspaceAddMutation,
  type WorkspaceAddPrecondition,
  type WorkspaceBlobPrecondition,
  type WorkspaceCloseEvidence,
  type WorkspaceCursor,
  type WorkspaceDeleteMutation,
  type WorkspaceDiffOutcome,
  type WorkspaceDiffRequest,
  type WorkspaceEvent,
  type WorkspaceExistingPrecondition,
  type WorkspaceGenerationPrecondition,
  type WorkspaceHandle,
  type WorkspaceHandleSnapshot,
  type WorkspaceIngestionAcceptAction,
  type WorkspaceIngestionAcceptScope,
  type WorkspaceIngestionCommand,
  type WorkspaceIngestionOutcome,
  type WorkspaceIngestionReceipt,
  type WorkspaceLifecycle,
  type WorkspaceListOutcome,
  type WorkspaceListRequest,
  type WorkspaceModifyMutation,
  type WorkspaceMutation,
  type WorkspaceMutationOutcome,
  type WorkspaceMutationRefusalReason,
  type WorkspacePathScope,
  type WorkspaceQuota,
  type WorkspaceQuotaState,
  type WorkspaceReadAction,
  type WorkspaceReadOutcome,
  type WorkspaceReadRequest,
  type WorkspaceReadScope,
  type WorkspaceRenameMutation,
  type WorkspaceSnapshot,
  type WorkspaceWriteAction,
  type WorkspaceWriteScope,
} from './contracts.js';
export {
  createMemoryWorkspace,
  type CreateMemoryWorkspaceOptions,
  type WorkspaceClock,
  type WorkspaceIdFactory,
} from './memory.js';
export {
  WorkspaceIdSchema,
  WorkspaceLineageIdSchema,
  WorkspaceSnapshotIdSchema,
  type WorkspaceId,
  type WorkspaceLineageId,
  type WorkspaceSnapshotId,
} from '../work-values.js';
export {
  WORKSPACE_CONFORMANCE_CASES,
  WORKSPACE_CONFORMANCE_VERSION,
  runWorkspaceConformance,
  type FailedWorkspaceConformanceCase,
  type PassedWorkspaceConformanceCase,
  type WorkspaceConformanceCase,
  type WorkspaceConformanceCaseId,
  type WorkspaceConformanceCaseResult,
  type WorkspaceConformanceExecution,
  type WorkspaceConformanceFixture,
  type WorkspaceConformanceReport,
  type WorkspaceConformanceTarget,
} from './conformance.js';
