/** @file Publishes Archer's action-bound Authority contracts and implementations. */

export {
  AUTHORITY_GRANT_ACTION,
  AUTHORITY_REVOKE_ACTION,
  AuthorityError,
  AuthorityLedgerIdSchema,
  AuthorizationGrantIdSchema,
  GrantRevocationIdSchema,
  GrantRevocationReasonSchema,
  PrincipalIdSchema,
  PrincipalSchema,
  authorityJsonScope,
  authorityTimestamp,
  createBootstrapAuthorizationGrant,
  defineAuthorityAction,
  type AttenuateGrantCommand,
  type AuthorityActionDefinition,
  type AuthorityAdministrationScope,
  type AuthorityBroker,
  type AuthorityBrokerCloseEvidence,
  type AuthorityCheck,
  type AuthorityClock,
  type AuthorityCommandRefusal,
  type AuthorityCommandRefusalReason,
  type AuthorityDecision,
  type AuthorityErrorCode,
  type AuthorityGrantAction,
  type AuthorityLedger,
  type AuthorityLedgerId,
  type AuthorityLedgerOptions,
  type AuthorityRefusal,
  type AuthorityRefusalReason,
  type AuthorityRevokeAction,
  type AuthorityVerification,
  type AuthorizationGrant,
  type AuthorizationGrantId,
  type AuthorizationGrantOrigin,
  type BootstrapAuthorizationGrantInput,
  type GrantCommand,
  type GrantOutcome,
  type GrantRef,
  type GrantRevocation,
  type GrantRevocationId,
  type Principal,
  type PrincipalId,
  type ProtectedAction,
  type ProtectedActionName,
  type RevokeGrantCommand,
  type RevokeGrantOutcome,
  type ScopeFor,
} from './contracts.js';
export { createMemoryAuthorityLedger } from './memory.js';
export { evaluateAuthority, type AuthorityEvaluationFacts } from './model.js';
