/** @file Publishes provider-neutral model configuration and one-step contracts. */

export { ModelsError, type ModelsErrorCode } from './errors.js';
export {
  compatibleModel,
  googleModel,
  modelDigest,
  modelRef,
  ollamaModel,
  openAIModel,
  reviseModel,
  xAIModel,
  type CompatibleModel,
  type CompatibleModelInput,
  type GoogleModel,
  type GoogleModelInput,
  type GoogleThinking,
  type Model,
  type ModelBase,
  type ModelCreationContext,
  type ModelId,
  type ModelRef,
  type ModelRevisionContext,
  type ModelRevisionId,
  type OllamaModel,
  type OllamaModelInput,
  type OpenAIModel,
  type OpenAIModelInput,
  type ReviseModelInput,
  type XAIModel,
  type XAIModelInput,
} from './targets.js';
export {
  createModelStepRequest,
  type CreateModelStepRequestInput,
  type ModelAttemptId,
  type ModelMessage,
  type ModelOutputPart,
  type ModelRouter,
  type ModelRouterCloseEvidence,
  type ModelStepCloseEvidence,
  type ModelStepEvent,
  type ModelStepRequest,
  type ModelStepRequestContext,
  type ModelStepRequestId,
  type ModelStepResourceSetRef,
  type ModelStepResult,
  type ModelStepStartOptions,
  type ModelToolDefinition,
  type ModelUsage,
} from './contracts.js';
